### ISSUE TITLE
Confusion matrix illustrate  

### ISSUE THREAD

**Issue by nandita96** [Altimis/Confusion-matrix-for-Matterport-implementation-of-Mask-R-CNN#1]
Hello Altimis,
My train data=476, Val data=95
Received : mAP =1, Precision=75% recall =63%
NUM_CLASSES = 1 + 2   (2 class and 1 background)  

I referred your code for confusion matrix, I am confuse what is this confusion matrix is illustrating in percentage, can you please tell inferences of below confusion matix?

![image](https://user-images.githubusercontent.com/55593006/89335970-a0d26880-d690-11ea-8314-ca49f085cb3d.png)

Thanks in advance

**Comment by nandita96** [comment]
@Altimis  looking forward get your reply as soon as possible as i have my submission to submit in coming week.  
i will be grateful to you.

**Comment by Altimis** [comment]
Hi @nandita96, I'm sorry for the late response. 

Actually, class 1 where you have 0.00% in both axes is referred to the background. The horizontal axis represents the ground-truth classes and the vertical axis represents the predicted classes. In your case, your model detected 94 objects of class 2 among the 98 objects existing in the data, the other 4 objects were identified as 3 objects of class 3 and one object of class 1 (as I said, class 1 is the background, which means that the model could not detect this object at all). The class 3 objects that exist in your images were all detected correctly (95/95 = 100%) but on the other hand, the model detected 6 other objects from the background that they are considered to be class 3 (101 detections = 95 + 6), 3 objects of class 2 and 3 objects of class 1 (the model detected 3 objects in the background as being of class 3 which are not). In conclusion, the horizontal axis represents the precisions of each class, and the vertical axis represents the recall of each class (the only reason I added the class background in the matrix is to define false positives and false negatives).

However, I still have some uncertainty about the function that computes the mAP. I will provide some time to review it.

I hope this will help.

**Comment by nandita96** [comment]
@Altimis 
 i am working on medical data,  as you said vertical axis represents the recall (FN) of each class and horizontal axis represents the precisions (FP) of each class. on that basis i concluded below things,  M i concluding correct ?????

will it work like that? but recall is higher than precision, i am doubt my model performance showing correct or wrong? please given your suggestion on this: 

According to above confusion matrix :
class 2 has:
precision  = 94.95% and recall = 95.92%

class 3 has:
precision  = 94.06% and recall = 100%

**Comment by Altimis** [comment]
> @Altimis
> i am working on medical data, as you said vertical axis represents the recall (FN) of each class and horizontal axis represents the precisions (FP) of each class. on that basis i concluded below things, M i concluding correct ?????
> 
> will it work like that? but recall is higher than precision, i am doubt my model performance showing correct or wrong? please given your suggestion on this:
> 
> According to above confusion matrix :
> class 2 has:
> precision = 94.95% and recall = 95.92%
> 
> class 3 has:
> precision = 94.06% and recall = 100%

In fact, what you mentioned in your first sentence is correct (vertical axis represents the recall (FN) of each class and horizontal axis represents the precisions (FP) of each class), but i think that when u came to apply this on your matrix, you confused the recall with precision (correct me if I'm wrong please). 

class 2 has:
precision = 95.92% (horizontal axis) and recall = 94.95% (vertical axis)

class 3 has:
precision = 100% (horizontal axis) and recall = 94.06% (vertical axis)

**Comment by Altimis** [comment]
@nandita96  Did my comment help you ? So that i can close this issue.

**Comment by nandita96** [comment]
@Altimis ,  yes i able to calculate F1 score from it. Thank you so much Altimis for helping me 😊🙌... yes you can close this issue. 
one thing i wanted to F1 score  is Disc score , is both are same?

**Comment by Altimis** [comment]
In fact, I've never worked with this DISC score, but F1 is easy to calculate : the F1 score of each class i is 2 * (precision(i) * recall(i)) / (precision(i) + recall(i)).
