### ISSUE TITLE
Precision-Recall curve

### ISSUE THREAD

**Issue by denashamss** [Altimis/Confusion-matrix-for-Matterport-implementation-of-Mask-R-CNN#2]
Dear Altimis,
Many thanks for the code you provided it was really helpful, I got the confusion matrix and TP,FP and FN, but the precision recall curve does not show anything for me. do you know how can I solve this issue?
![download (2)](https://user-images.githubusercontent.com/61122633/96733902-f4974880-1387-11eb-9fca-87216db9aa36.png)

**Comment by Altimis** [comment]
Hi, sorry for this late response. In fact, I'v just checked the code I provided and found out that the methode I used to calculate the Average Precision and plot the Precision-Recall is not the right way to do so. The only thing I'm pretty sure about is the methode I used to calculate TP, FP and FN and plot the confusion matrix. I recommand to check this [repo ](https://github.com/Altimis/Object-Detection-Metrics).

**Comment by denashamss** [comment]
Many thanks
