### ISSUE TITLE
false positives and false negatives seem mixed up

### ISSUE THREAD

**Issue by godfrey-scalpel** [Altimis/Confusion-matrix-for-Matterport-implementation-of-Mask-R-CNN#7]
https://github.com/Altimis/Confusion-matrix-for-Mask-R-CNN/blob/ea4134e4e31a0f43d1a96384ce2234553152bc9e/utils.py#L346

**Comment by Altimis** [comment]
Yes it's true

**Comment by AIprototype** [comment]
Yea it is reversed, I hope just changing the fn and fp lists will be enough to fix it?

**Comment by Altimis** [comment]
Yes done
