### ISSUE TITLE
AttributeError: module 'mrcnn.utils' has no attribute 'gt_pred_lists'

### ISSUE THREAD

**Issue by nataliameira** [Altimis/Confusion-matrix-for-Matterport-implementation-of-Mask-R-CNN#8]
Hello
I copied your code to the end of my utils.py file.

I tried to calculate the mAP. I get this error:

`AttributeError: module 'mrcnn.utils' has no attribute 'gt_pred_lists'`

Your help will be appreciated.

**Comment by Altimis** [comment]
The gt_pred_lists exists in the utils file. Maybe you forgot to copy it or you didn't save the file before executing.

**Comment by nataliameira** [comment]
Thanks @Altimis 

I found the problem. My Notebook jupyter was not loading the changes made in utils.py.

Now it worked. However, all my mAP results are given zero.

Do you know why?
![map zero](https://user-images.githubusercontent.com/56967314/128407713-51bd5c07-54db-417b-a5bb-467889e6d4ca.PNG)

**Comment by AIprototype** [comment]
@nataliameira I implemented this and the mAP was being correctly computed, I have am including the python method I have defined from @Altimis notebook

`    def plot_confusion_matrix(self, class_names):
        # ground-truth and predictions lists
        gt_tot = np.array([])
        pred_tot = np.array([])
        # mAP list
        mAP_ = []
        for image_id in self.dataset.image_ids:
            image, image_meta, gt_class_id, gt_bbox, gt_mask = \
                modellib.load_image_gt(self.dataset, self.cfg, image_id, use_mini_mask=False)
            info = self.dataset.image_info[image_id]

            # Run the model
            results = self.model.detect([image], verbose=1)
            r = results[0]

            # compute gt_tot and pred_tot
            gt, pred = gt_pred_lists(gt_class_id, gt_bbox, r['class_ids'], r['rois'])
            gt_tot = np.append(gt_tot, gt)
            pred_tot = np.append(pred_tot, pred)

            # precision_, recall_, AP_
            AP_, _, _, _= compute_ap(gt_bbox, gt_class_id, gt_mask,
                                                    r['rois'], r['class_ids'], r['scores'], r['masks'])

            # check if the vectors len are equal
            print("the actual len of the gt vect is : ", len(gt_tot))
            print("the actual len of the pred vect is : ", len(pred_tot))

            mAP_.append(AP_)
            print("Average precision of this image : ", AP_)
            print("The actual mean average precision for the whole images (matterport methode) ", sum(mAP_) / len(mAP_))
            # print("Ground truth object : " + self.dataset.class_names[gt])
            # print("Predicted object : " + self.dataset.class_names[pred])
        gt_tot = gt_tot.astype(int)
        pred_tot = pred_tot.astype(int)
        # save the vectors of gt and pred
        save_dir = "output"
        gt_pred_tot_json = {"gt_tot": gt_tot, "pred_tot": pred_tot}
        df = pd.DataFrame(gt_pred_tot_json)
        if not os.path.exists(save_dir):
            os.makedirs(save_dir)
        df.to_json(os.path.join(save_dir, "gt_pred_test.json"))

        # here i didnt set the columns list, since in the code if columns is note specified it generates
        # automatically a list from "class A" to "class ..". in this example, class A should be the background Note :
        # class A is the backround in this example
        tp, fp, fn = plot_confusion_matrix_from_data(gt_tot,
                                                     pred_tot,
                                                     fz=15,
                                                     figsize=(10, 10),
                                                     lw=0.3,
                                                     columns=class_names)
        # eliminate the background class (BG) from tps fns and fps lists since it doesn't concern us anymore :
        del tp[0]
        del fp[0]
        del fn[0]
        print(f'TP : {tp}')
        print(f'FP : {fp}')
        print(f'FN : {fn}')
        precision = tp[0] / (tp[0] + fp[0])
        recall = tp[0] / (tp[0] + fn[0])
        print(f'mAP : {sum(mAP_) / len(mAP_)}')
        print(f'Precision : {precision}')
        print(f'Recall : {recall}')
        print(f'F1 Score : {2 * precision * recall / (precision + recall)}')`

**Comment by Altimis** [comment]
Sorry for the late response. Actually, the ``compute_ap`` function is exactly the one that exists in the original utils.py. So if the AP of each image is equal to 0 it would mean that your model isn't performing well. Can you show me your confusion matrix please ?

**Comment by nataliameira** [comment]
@Altimis I solved my problem, thank you for your help!
